# Para tu archivo db.properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
db.username=postgres.kgryruuohejtgclexpgnc
db.password=1057980706Val.